language: python
python:
  - "3.6"

before_install:
  - pip install coverage
  - pip install python-coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-mpl
  - pip install -U numpy
  - python -c "import numpy; print(numpy.version.version)"
  - pip install -U matplotlib
  - pip install yt
  - pip install sigal
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran liblapack-pic
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - pip install -e .

install:

script:
  - cd $HOME/build/ketch/griddle
  - py.test --cov=griddle --doctest-modules --mpl --ignore=clawpack

after_success:
  - coveralls
