language: python
python:
  - "3.6"

addons:
  artifacts: true

before_install:
  - pip install coverage
  - pip install python-coveralls
    #- pip install -U Cython
  - pip install numpy
  - pip install matplotlib
  - pip install yt
  - pip install sigal
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran liblapack-pic
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - pip install -e .

install:

script:
  - cd $HOME/build/ketch/griddle
  - python tests.py -v --with-coverage --cover-package=griddle --with-doctest;

after_success:
  - coveralls
