language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install libhdf5-serial-dev
  - pip install coverage
  - pip install python-coveralls
  - pip install numpy
  - pip install matplotlib
  # yt and dependencies
  - pip install -U Cython
  - pip install sympy
  - pip install h5py
  - pip install yt
  - python -c "import yt; print yt.__version__"
  ####
  - pip install sigal
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran liblapack-pic
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - pip install -e .

install:

script:
  - cd $HOME/build/ketch/griddle
  - python tests.py -v --with-coverage --cover-package=griddle;

after_success:
  - coveralls
